name: Translator
version: 1.0.0
description: Translate your content with the click of a button
addon_url: https://github.com/aerni/statamic-translator
developer: 'Michael Aerni'
developer_url: 'https://www.michaelaerni.ch'
commercial: true
fieldtype_fields:
  button_text:
    type: text