fields:
  translation_service_section:
    type: section
    display: Translation Service
  translation_service:
    type: select
    display: Translation Service
    instructions: Choose your prefered translation service.
    options:
      google_basic: 'Google Cloud Translation – Basic (v2)'
      google_advanced: 'Google Cloud Translation – Advanced (v3)'
  google_basic_section:
    type: section
    display: Google Cloud Translation – Basic (v2)
    show_when:
      translation_service: google_basic
  google_translation_api_key:
    type: text
    display: Google Cloud Translation API Key
    instructions: Enter your Google Cloud Translation API Key.
    show_when:
      translation_service: google_basic
  google_advanced_section:
    type: section
    display: Google Cloud Translation – Advanced (v3)
    show_when:
      translation_service: google_advanced
  google_application_credentials:
    type: text
    display: Google Application Credentials
    instructions: Enter the path to your credentials file.
    show_when:
      translation_service: google_advanced
  google_cloud_project:
    type: text
    display: Google Cloud Project
    instructions: The name of your project.
    show_when:
      translation_service: google_advanced